// <auto-generated />
using System;
using MathExamWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MathExamWeb.Migrations
{
    [DbContext(typeof(MathExamDbContext))]
    [Migration("20260118085349_AddExamRecordsAndWrongQuestions")]
    partial class AddExamRecordsAndWrongQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MathExamWeb.Data.Models.ExamRecordEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<double>("AccuracyRate")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_rate");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers_json");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_exam_records_created_at");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("idx_exam_records_end_time");

                    b.HasIndex("Subject")
                        .HasDatabaseName("idx_exam_records_subject");

                    b.ToTable("exam_records");
                });

            modelBuilder.Entity("MathExamWeb.Data.Models.WrongQuestionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<bool>("IsMastered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mastered");

                    b.Property<DateTime?>("MasteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mastered_at");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("question_id");

                    b.Property<string>("QuestionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("question_json");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("question_type");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_answer");

                    b.Property<DateTime>("WrongAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("wrong_at");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_count");

                    b.HasKey("Id");

                    b.HasIndex("IsMastered")
                        .HasDatabaseName("idx_wrong_questions_is_mastered");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("idx_wrong_questions_question_id");

                    b.HasIndex("Subject")
                        .HasDatabaseName("idx_wrong_questions_subject");

                    b.HasIndex("WrongAt")
                        .HasDatabaseName("idx_wrong_questions_wrong_at");

                    b.HasIndex("Subject", "QuestionText")
                        .HasDatabaseName("idx_wrong_questions_subject_text");

                    b.ToTable("wrong_questions");
                });

            modelBuilder.Entity("MathExamWeb.Data.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<bool>("IsFractionAnswer")
                        .HasColumnType("boolean")
                        .HasColumnName("IsFractionAnswer");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_questions_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_questions_created_at");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("idx_questions_difficulty");

                    b.HasIndex("Subject")
                        .HasDatabaseName("idx_questions_subject");

                    b.ToTable("questions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
